swagger: '2.0'

info:
  description: 自控力API
  version: 1.0.0
  title : Self_Control API
  contact: 
    name: TAODEI
    email: 864978550@qq.com
host: localhost
basePath: /api/v1
tags: 
  - name: user
    description: 用户
  - name: punch
    description: 打卡
schemes:
  - http
  - https

paths: 

  /login:
    post:
      tags:
        - user
      summary: 登录
      description: 学号密码登录
      parameters:
        - name: data
          in: body
          description: post data
          schema:
            required:
              - student_id
              - password
            properties:
              student_id:
                type: string
                description: 学号
              password:
                type: string
                description: 密码
      responses:
        200:
          description: 登录成功
          schema:
            properties:
              token:
                type: string
                description: 将student_id作为token保留
        400:
          description: 参数或客户端语法有误
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: 用户名或密码错误
          schema:
            type: object
            properties:
              message:
                type: string
          
  /punchs/{type}:
    get:
      tags:
        - punch
      summary: 显示当前类型所有打卡
      parameters: 
        - name: type
          in: path
          required: true
          type: string
      responses:
        200: 
          description: 成功 
          schema:
            properties:
              punch:
                type: array
                items:
                  properties:
                    icon:
                      type: string
                    title:
                      type: string
        400:
          description: 参数或客户端语法有误
          schema:
            type: object
            properties:
              message:
                type: string
              
  /user/punchs:
    get:
      tags: 
        - user
      summary: 用户主页-已选标签
      parameters: 
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:   
            properties:
              punch:
                type: array
                items:
                  properties:
                    title:
                      type: string
                    icon:
                      type: string
                    choice:
                      type: boolean
                      description: 是否选择
                      
        400:
          description: 参数或客户端语法有误
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误
          schema:
            type: object
            properties:
              message:
                type: string
          
  /user:
    get:
      tags:
        - user
      summary: 用户主页
      parameters:
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:
            properties:
              name: 
                type: string
              user_picture:
                type: string
        404:
          description: 没有该资源
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误，没有权限
          schema:
            type: object
            properties:
              message:
                type: string
    put:
      tags:
        - user
      summary: 修改用户信息
      parameters:
        - $ref: "#/parameters/token"
        - name: data
          in: body
          schema:
            properties:
              user_picture:
                type: string
                description: 头像图片的url
              name:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误
          schema:
            type: object
            properties:
              message:
                type: string
          
  /user/gold:
    get:
      tags:
        - user
      summary: 获取金币数及使用历史
      parameters:
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:
            properties:
              gold:
                type: integer
              history:
                type: array
                items:
                  properties:
                    time:
                      type: string
                    reason: 
                      type: string
                    change_number:
                      type: integer
                      
        404:
          description: 没有该资源
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误，没有权限
          schema:
            type: object
            properties:
              message:
                type: string
          
          
  /user/achievement:
    get:
      tags:
        - user
      summary: 获取过往成就
      parameters:
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:
            properties:
              name: 
                type: string
              achievement:
                type: array
                items:
                  properties:
                    content:
                      type: string
        404:
          description: 没有该资源
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误，没有权限
          schema:
            type: object
            properties:
              message:
                type: string
          
  /punch: 
    get:
      tags:
        - punch
      summary: 我的打卡
      parameters:
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:
            type: array
            items:
              properties:
                icon:
                  type: string
                title:
                  type: string
                number:
                  type: integer
                choice:
                  type: boolean
                  description: 今日是否已经打卡
        401:
          description: token错误，没有权限
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      tags:
        - punch
      summary: 完成打卡
      parameters:
        - $ref: "#/parameters/token"
        - name: punch
          in: body
          schema:
            properties:
              title:
                type: string
      responses:
        200:
          description: 打卡成功
          schema:
            type: object
            properties:
              message:
                type: string
          
        400:
          description: 打卡失败，今日已打卡
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误
          schema:
            type: object
            properties:
              message:
                type: string
        
        
      
      
    delete:
      tags:
        - punch
      summary: 移除标签
      parameters:
        - $ref: "#/parameters/token"
        - name: punch
          in: body
          schema:
            properties:
              title:
                type: string
      responses:
        200:
          description: 移除成功
          schema:
            type: object
            properties:
              message:
                type: string
          
        400:
          description: 移除失败
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误
          schema:
            type: object
            properties:
              message:
                type: string
  /list:
    get:
      summary: 排行榜
      parameters: 
        - name: time
          in: header
          required: true
          type: number
      responses:
        200:
          description: 获取成功
          schema:
            type: array
            items:
              properties:
                user_picture:
                  type: string
                  description: 头像图片的url
                punch_number:
                  type: integer
        404:
          description: 无资源
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      summary: 兑换排名
      parameters:
        - name: rank_id
          in: body
          schema:
            properties:
              id:
                type: integer
      responses:
        200:
          description: 兑换成功
          schema:
            type: object
            properties:
              message:
                type: string
            
        400: 
          description: 金币不足或已为该排名
          schema:
            type: object
            properties:
              message:
                type: string
  
  /user/punch:
    get:
      tags:
        - user
      summary: 用户打卡数和天数
      parameters: 
        - $ref: "#/parameters/token"
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              properties:
                title:
                  type: string
                number:
                  type: integer
                time:
                  type: number
        401:
          description: token错误
          schema:
            type: object
            properties:
              message:
                type: string
  
  /backdrop:
    get:
      summary: 背景兑换价格
      responses:
        200: 
          description: 获取成功
          schema:
            type: array
            items:
              properties:
                backdrop_id:
                  type: integer
                picture_url:
                  type: string
                gold:
                  type: integer
        400:
          description: 无资源
          
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      summary: 兑换背景
      parameters:
        - name: backdrop_id
          in: body
          schema:
            properties:
              id:
                type: integer
      responses:
        200:
          description: 兑换成功
          schema:
            type: object
            properties:
              message:
                type: string
            
        400: 
          description: 金币不足或已拥有该背景
          schema:
            type: object
            properties:
              message:
                type: string
          
  /privacy:
    post:
      summary: 打卡内容公开与否
      parameters:
        - name: choice
          in: body
          schema: 
            properties:
              choice: 
                type: boolean
      responses:
        200:
          description: 选择成功
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: token错误，没有权限
          schema:
            type: object
            properties:
              message:
                type: string 
 

parameters:
  token:
      name: token
      in: header
      required: true
      type: string  

