local_name: SC
runmode: release             # 开发模式, debug, release, test
addr: 127.0.0.1:8080
port: :8080
db:  # DB 配置 部署时环境变量覆盖
  name: SC
  addr: 127.0.0.1:3306
  username: root
  password: 12345678
oss:
  access_key: 0bNiwJGpdwmvvuVAzLDjM6gnxj9MiwmSagVpIW81
  secret_key: zHA9w8PoSfL6D4dvWNwU2GF4XHUn9MalynbANE3_
  bucket_name: self-control
  domain_name: http://r9rosthyx.hn-bkt.clouddn.com # 临时域名