local_name: SC
runmode: release             # 开发模式, debug, release, test
addr: 127.0.0.1:8080
port: :8088
db:  # DB 配置 部署时环境变量覆盖
  name: SC
  addr: 127.0.0.1:3306
  username: root
  password: 12345678